apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: copy-assets-template
spec:
  serviceAccountName: argo
  templates:
    - name: copy-task
      container:
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: copy-stac-asset-s3-secret
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: copy-stac-asset-s3-secret
              key: secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: copy-stac-asset-s3-secret
              key: region
        image: quay.io/element84/copy-assets-stac-task:latest
        imagePullPolicy: IfNotPresent
        command: ["python3", "./task.py", "run"]
        args: ["{{workflow.parameters.input}}"]
