apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: copy
spec:
  entrypoint: copy-assets
  serviceAccountName: argo # set this so the proper permissions are assigned
  arguments:
    parameters:
    - name: input
      value: https://payloadtest.s3.us-west-2.amazonaws.com/payload_workflow.json

  templates:
  - name: copy-assets
    inputs:
      parameters:
      - name: input       # parameter declaration
    container:
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-secret-credentials
            key: access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret-credentials
            key: secret_access_key
      image: quay.io/element84/copy-assets-stac-task:latest
      imagePullPolicy: IfNotPresent
      command: ["python3", "./task.py", "run"]
      args: ["{{inputs.parameters.input}}"]
